version: 2.1

jobs:
  post-coverage-comment:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: .circleci/post_coverage_comment.sh

workflows:
  new-pr:
    jobs:
      - run: .circleci/post_coverage_comment.sh <<pipeline.event.github.pull_request.number>>